### PR TITLE
Display leaderboard ranks 1/2/3 as gold/silver/bronze

### PR DESCRIPTION
**Pull request by aguibert**
image

### CODE REVIEW

**Comment by realModusOperandi** [comment]
Good idea!

The transparency of the background color seems to be causing the gold/silver/bronze colors to pick up a cast. I've tried to come up with darker colors to use at full opacity instead but what I tried just winds up coming out drab.

Instead, how about changing the foreground colors instead of the background. This would allow us to use bright colors without being overly distracting:

screen shot 2018-05-26 at 7 28 48 pm

However, the silver is very hard to distinguish from a normal rank entry and really, color shouldn't be the only distinguishing aspect of an element. I was thinking we could add a border:

screen shot 2018-05-26 at 7 28 04 pm

or if the full border is too heavy, how about just across the bottom:

screen shot 2018-05-26 at 7 36 19 pm

Another idea I had was to do a circle background for the rank column for the top 3 ranks, with black text for the number on top of a gold/silver/bronze circle, but that would take some time to get right.

Thoughts?

**Comment by aguibert** [comment]
I like the 2nd screenshot the best out of the three, only comment I have is that the bronze looks too much like orange (might get confused with the orange color player).  So making it darker / more brown would help differentiate the two color meanings

**Comment by realModusOperandi** [comment]
Okay, I have these colors:

screen shot 2018-05-27 at 7 45 19 am

Gold: `color: #f7df69;`
Silver: `color: #e7e7e7;`
Bronze: `color: #d68432;`

How's that?

**Comment by realModusOperandi** [comment]
Closing as these changes were delivered under #125

**Pull request closed without merging**
